### PR TITLE
HTML and CSS guidelines

### PR DESCRIPTION
**Pull request by schettn**
- Add code guide for HTML and CSS

### CODE REVIEW

**Comment by schettn** [comment]
@Aichnerc please check if this makes sense or we should add this elsewhere in the guide.

**Review by Aichnerc — APPROVED** [review]
🎐

**Review by pinterid — APPROVED** [review]
Looks good.

**Comment by pinterid** [comment]
Can we create an issues for the changes of the pull request and link it to the pull request.

**Pull request merged**
